---
galaxy_info:
  author: Jasper N. Brouwer, Ramon de la Fuente
  description: Install nodejs and npm
  company: Future500
  license: LGPL
  min_ansible_version: 1.4
  platforms:
  - name: Debian
    versions:
      - wheezy
  - name: Ubuntu
    versions:
      - all
  categories:
    - web
    - system
    - packaging
dependencies: []
